set nocompatible
set number

filetype plugin indent on
syntax on

colorscheme dark_plus

set autoindent             " Indent according to previous line.
set autoread
set noswapfile
set nowrap
set smarttab
set tabstop=4
set shiftwidth=4
set encoding=utf-8
set fileencodings=utf-8,chinese,latin-1
set cursorline
" set omnifunc=syntaxcomplete#Complete
set completeopt=menu,menuone,noselect,noinsert
set splitbelow
set splitright
set backspace=indent,eol,start
set hidden
set laststatus  =2
set display     =lastline
set showmode
set showcmd
set lazyredraw
set scrolloff=5
set hlsearch
set foldmethod=indent
set nofoldenable
set runtimepath+=~/.vim/mysnippets

" set incsearch
let mapleader = "\<Space>"

let g:rustfmt_autosave = 0
let g:syntastic_rust_checkers = []

" let g:ale_rust_rls_toolchain = 'stable'
let g:ale_linters = {
\   'go': ['govet'],
\   'rust': ['cargo'],
\}
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_enter = 1
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'rust': ['rustfmt'],
\   'go': ['goimports'],
\}
let g:ale_fix_on_save = 1
let g:ale_close_preview_on_insert = 1
let g:ale_rust_cargo_default_feature_behavior = 'all'

let g:nerdtree_tabs_open_on_console_startup = 1
let g:NERDTreeChDirMode = 2
let NERDTreeHighlightCursorline = 1
let NERDTreeShowLineNumbers = 1


" set wildignore+=*/target/*
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]((\.(git|hg|svn))|target)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': '',
  \ }
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }

let g:ackprg = 'ag --nogroup --nocolor --column --ignore-dir target'
let g:ack_autoclose = 1

let g:ycm_min_num_of_chars_for_completion = 2
let g:ycm_min_num_identifier_candidate_chars = 2
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_key_list_stop_completion = ['<enter>']
let g:ycm_filetype_whitelist = {'rust': 1, 'c': 1, 'go': 1}
let g:ycm_racerd_binary_path = 'racerd'
let g:ycm_goto_buffer_command = 'split-or-existing-window'
" let g:ycm_goto_buffer_command = 'split'
" let g:ycm_goto_buffer_command = 'same-buffer'
let g:ycm_semantic_triggers = get(g:, 'ycm_semantic_triggers', {})
let g:ycm_semantic_triggers.rust = ['.', ':', 're![\w-]{2}']
let g:ycm_semantic_triggers.go = ['.', 're![\w-]{2}']
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_echo_current_diagnostic = 0
let g:ycm_show_diagnostics_ui = 0
let g:ycm_enable_diagnostic_signs = 0
let g:ycm_enable_diagnostic_highlighting = 0

let g:ycm_language_server =
  \ [
  \   {
  \     'name': 'rust',
  \     'cmdline': [ 'rls' ],
  \     'filetypes': [ 'rust' ]
  \   },
  \   {
  \     'name': 'go',
  \     'cmdline': [ 'gopls' ],
  \     'filetypes': [ 'go' ]
  \   }
  \ ]

let g:UltiSnipsExpandTrigger="<C-e>"
let g:UltiSnipsListSnippets='<C-space>'
let g:UltiSnipsJumpForwardTrigger="<C-j>"
let g:UltiSnipsJumpBackwardTrigger="<C-k>"

let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 0
let g:NERDTrimTrailingWhitespace = 1

let g:go_fmt_autosave = 0
let g:go_fmt_command = "goimports"
let g:go_def_reuse_buffer = 1
let g:go_def_mapping_enabled = 0
let g:go_def_mode = 'gopls'
let g:go_info_mode = 'gopls'


packloadall
silent! helptags ALL

inoremap <silent> jk <ESC>
inoremap <silent> zz <ESC>o
inoremap <silent> xx <ESC>O
inoremap <silent> ;; <ESC>A
inoremap <silent> ;] <ESC>]}a
inoremap <silent> ;) <ESC>2])a
nnoremap <silent> zz :update<CR>

nnoremap <c-h> ^
nnoremap <c-l> $
vnoremap <c-h> ^
vnoremap <c-l> $
inoremap <c-l> <c-o>a

vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P

nmap <Leader>x gt
nmap <Leader>z gT

nmap <Leader>b :vnew<CR>

vnoremap <silent> y y`]
sunmap y
vnoremap <silent> p p`]
sunmap p
nnoremap <silent> p p`]

vmap <Leader>( S(
vmap <Leader>[ S[
vmap <Leader>{ S{
vmap <Leader>" S"
vmap <Leader>' S'
vmap <Leader>` S`

" CompleteParameters
inoremap <silent><expr> <C-f> complete_parameter#pre_complete("()")
smap <c-j> <Plug>(complete_parameter#goto_next_parameter)
imap <c-j> <Plug>(complete_parameter#goto_next_parameter)
smap <c-k> <Plug>(complete_parameter#goto_previous_parameter)
imap <c-k> <Plug>(complete_parameter#goto_previous_parameter)

nnoremap <silent> gvt :vert term<CR>
nnoremap <silent> gc :let @/ = ""<CR>
nnoremap <Leader>s :Ack!<SPACE>
nnoremap gq :cclose<CR>

nmap gd :vertical YcmCompleter GoTo<CR>
nmap <Leader>gd :tab YcmCompleter GoTo<CR>

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
nnoremap tt :NERDTreeToggle<CR>
nnoremap tm :NERDTreeMirror<CR>
nnoremap tf :NERDTreeFocus<CR>

au FileType rust nnoremap gh :ALEHover<CR>
au FileType rust nnoremap ga :ALEDetail<CR>
au FileType rust nnoremap <Leader>al O<ESC>dd:update<CR>

au FileType go set omnifunc=""

call NERDTreeAddKeyMap({'key': 't', 'callback': 'NERDTreeMyOpenInTab', 'scope': 'FileNode', 'override': 1 })
function NERDTreeMyOpenInTab(node)
    call a:node.open({'reuse': "all", 'where': 't'})
endfunction
