theme = "dark_plus"

[editor]
mouse = false
true-color = true
bufferline = "multiple"
auto-info = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]

[editor.search]
smart-case = false

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.gutters.line-numbers]
min-width = 1

# INSERT MODE
[keys.insert]
z = { z = ["normal_mode", "open_below"] }
x = { x = ["normal_mode", "open_above"] }
# ";" = { ";" = ["normal_mode", "insert_at_line_end"] }
C-l = ["normal_mode", "move_char_right", "insert_mode"]
C-h = ["normal_mode", "move_char_left", "insert_mode"]
j = { k = "normal_mode" }

# NORMAL MODE
[keys.normal]
C-j = "goto_next_diag"
C-k = "goto_prev_diag"
C-h = "goto_first_nonwhitespace"
C-l = "goto_line_end"
z = { z = ":write" }

[keys.normal.g]
d = ["vsplit", "goto_definition"]

[keys.normal.s]
s = "surround_add"
d = "surround_delete"
r = "surround_replace"

[keys.normal.space]
q = [":bc", "wclose"]
