# snippets see: https://github.com/rafamadriz/friendly-snippets
[language-server.scls]
command = "simple-completion-language-server"
config = { max_completion_items = 20, snippets_first = true }

[language-server.gopls]
command = "gopls"
config = { "ui.completion.usePlaceholders" = true }

[[language]]
name = "go"
language-servers = [ "gopls" ]

[[language]]
name = "rust"
language-servers = [ "scls", "rust-analyzer" ]
